HelloWorld-Microverse
M-Anwar-Hussaini/HelloWorld-Microverse pull request #1
Opened 2023-04-25 19:15 UTC by M-Anwar-Hussaini

Hi dear Code Reviewer.

I tried my best to fix the issues you mentioned in the first PR. I hope they are all fixed.
If there are some some problems please do mention me so that I consider in the future projects.

Thanks a lot.

2023-04-25 21:55 UTC, usorfaitheloho requested changes
Hi @M-Anwar-Hussaini , 

>You are almost there!
Great effort so far, but unfortunately there are some issues that you need to review in order to get your project approved, but you got this!


![Alt Text](https://camo.githubusercontent.com/59fa9d95c18dbd5a8e47490a9e4b48393f569685410f3c78d4d83a9764fa1392/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f74385950663341434b656f754c7a454976722f67697068792e676966)
>


## Highlights
- Correct GitHub flow was used :100: 
- Linter checks are passing :100: 
<br/>
<br/>
<br/>

## Required Changes ♻️
- [x] Please add a descriptive Pull Request Title and summary using the project details to give a better understanding of the changes you introduced in this milestone.
- [x]  You did great using the right Microverse README template, please always remember to only use the sections that are relevant to your project and fill all sections with the appropriate content relative to the work you did for the project.

- [x] As part of the requirements, please create a `test. md` file in the root directory of your repository. You did well in adding it to the `.gitignore` file so go ahead and create it in your project

![test md](https://user-images.githubusercontent.com/20537712/234386963-2a6314d8-b61f-47a4-8b45-23c796c8407c.png)


_Check the comments below to see technical issues found during this review._

## Optional suggestions


- [x] Please ensure you use descriptive branch names that summarize the features you implemented in a repository, and for each commit message  also use good and imperative commit messages giving reasons for the actions completed in the description

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
<br/>


You can also try reaching me on Slack, looking for me as `@Javier Hernandez`

Cheers and Happy coding!👏👏👏
<br/>
<br/>
<br/>
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 21:55 UTC, usorfaitheloho commented on README.md
I'd kindly suggest you remove all comments, and descriptive lines in the README file to make your code legible and easy to understand 😄 . You should also edit the contents of all required sections with the right details of your project, you did well with the `authors` section so please implement the remaining sections 👍

2023-04-25 22:05 UTC, M-Anwar-Hussaini commented
Thanks.
I will figure it out.

2023-04-25 23:06 UTC, Efiamotu-1 requested changes
Hi @M-Anwar-Hussaini , 

![](https://camo.githubusercontent.com/a06454929d29b512682cd8b375641b59076b9e5fe1a367808e685e5bcb818de3/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f76312e59326c6b505463354d4749334e6a45784e32466d5957466c5a6a45794d7a49314f4455784d5455775a44686b595459355932526c4e6a4d334e7a4e6c4f574530596a4a684d695a6c634431324d563970626e526c636d35686246396e61575a7a583264705a6b6c6b4a6d4e305057632f7a3370696f6b77663057504838314d4f68752f67697068792e676966)

Great work on making the changes requested by a previous reviewer 👏 Your Code is Awesome! 💪
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Especially if that's is your first project 1️⃣. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better job** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- Good job implementing some of the requirements of the first reviewer :+1: 
- ✔️ No linter Errors
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-25 23:06 UTC, Efiamotu-1 commented on README.md
- [ ] Please kindly work on Your readme file as it is currently not looking very professional. It is great you used the [Microverse readme template](https://github.com/microverseinc/readme-template) but you didn't follow it to the latter. Every section of the template is required to appear on your read me and you are to customise the template with your github repo details as well as details needed for better description of the project. :+1: 
 - [ ] Your readme is currently missing the following sections `Getting started, setup, prerequisites, install, usuage, run tests, deployment, future features, contributing, show your support` please kindly add them before opening a new pull request. :+1:

2023-04-25 23:06 UTC, Efiamotu-1 commented on README.md
> -
please Kindly remove these texts as they only serve descriptive purposes which are to guide you on how to customise this section of your readme file, once customized to your taste as you have done you do not need them anymore and you can take it off +1

2023-04-25 23:06 UTC, Efiamotu-1 commented on README.md
please Kindly remove these texts as they only serve descriptive purposes which are to guide you on how to customise this section of your readme file, once customized to your taste as you have done you do not need them anymore and you can take it off :+1:

2023-04-25 23:06 UTC, Efiamotu-1 commented on README.md
>  <!-- PROJECT DESCRIPTION -->
- [ ] comments are unused code which do not make your project look professional, do well to remove them :+1:

2023-04-25 23:06 UTC, Efiamotu-1 commented on README.md
> -<summary>Database</summary>
- [ ] Kindly ensure that you are using the correct technologies you used in building this project as it is more descriptive and anyone even recruiters can use and test your projects. :+1:

2023-04-25 23:06 UTC, Efiamotu-1 commented on README.md
please Kindly remove these texts as they only serve descriptive purposes which are to guide you on how to customise this section of your readme file, once customized to your taste as you have done you do not need them anymore and you can take it off :+1:

2023-04-25 23:06 UTC, Efiamotu-1 commented on README.md
> -
- [ ] You are required to list at least 2-3 features which you implemented on this branch please try to do this as it is professional and shows how much you progress with your work with every given branch :+1:

2023-04-25 23:06 UTC, Efiamotu-1 commented on README.md
> -
please Kindly remove these texts as they only serve descriptive purposes which are to guide you on how to customise this section of your readme file, once customized to your taste as you have done you do not need them anymore and you can take it off :+1:

2023-04-25 23:06 UTC, Efiamotu-1 commented on README.md
> -- [Live Demo Link](https://google.com)
- [ ] Kindly notify users when the live demo is not ready or if it won't be implemented. This prevents your Readme from having broken links :+1:

2023-04-25 23:06 UTC, Efiamotu-1 commented on README.md
- [ ] please Kindly remove these texts as they only serve descriptive purposes which are to guide you on how to customise this section of your readme file, once customized to your taste as you have done you do not need them anymore and you can take it off :+1:

2023-04-25 23:06 UTC, Efiamotu-1 commented on index.html
- [ ] It is also important to use good PR title and summary when making a pull request attached below is an image of how your pr title and summary for this project should look like please make sure to make the correct changes before resubmitting for a new pull request. :+1: 
- [ ] Make sure to also name your branches descriptively tailored to the changes you would be making for example `add-homepage`, `mobile-menu-feature` etc
![good-pr](https://user-images.githubusercontent.com/89055502/234389170-2ece21cc-1ad3-46e1-8e31-cb39f5f8304d.png)

2023-04-25 23:34 UTC, M-Anwar-Hussaini commented on README.md
> -<summary>Database</summary>
Hi @Efiamotu-1 
Could you please explain this part with more details.

Thanks.

2023-04-25 23:39 UTC, Efiamotu-1 commented on README.md
> -<summary>Database</summary>
@M-Anwar-Hussaini the hello microverse project you submitted was built using html and css but what you have on your readme file here is showing reactJs, expressJs which you didn't use at all. so the change is basically for you to use the correct technologies which are html and css in your readme under the built with section. did you find the explanation helpful?

2023-04-26 00:37 UTC, taldr27 approved these changes
## Hi @M-Anwar-Hussaini , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉

![congrats](https://media.giphy.com/media/3o6fIUZTTDl0IDjbZS/giphy.gif)

## Highlights 🎉
✅ Professional and customized README. 
✅ Linters tests passing.
✅ Correct use of GitHub Flow.
✅ Incorporates feedback from previous code reviews.

## Optional suggestions 💭

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [ ] **[OPTIONAL]** You did a great job on this project, I just have a small suggestion to make your future pull requests even better, always try to write your pull request summary describing all the changes you made, I will tag you on the previous reviewer comment. 💯

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-04-26 00:41 UTC, taldr27 commented on index.html
- [ ] @M-Anwar-Hussaini Nice work making all the requested changes from previous reviewers, I just have one suggestion to make your pull request more professional in this and your future projects, always try to write your pull request summary like in the image provided by @Efiamotu-1. 💯

2023-04-26 04:34 UTC, merged